#!/usr/bin/env bash
code_root="/code/"
for dir in $code_root*/
do
    dir=${dir%*/}
    
    cd $code_root${dir##*/}
    if [ -d .git ]; then
		mod=$(git status --porcelain | wc -l)
		if [ $mod -gt 0 ]; then
			printf "\n\n"
			echo $code_root${dir##*/}
			echo "-----------------"
			git status 
			# git rm --cached *DS_Store
			# git commit -m 'removed junk'

		fi;
	# else
	# 	echo "Not a git repo!"
	fi;
    
done