#!/usr/bin/env python
# usage:
# assignIcon icon.png folder_to_assign_to

import Cocoa
import sys

Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_(sys.argv[1]), sys.argv[2], 0) or sys.exit("Unable to set file icon")