#!/bin/bash
# cron-update
# a script meant to be run by cron, which runs various routine update tasks
# 
# created by Srinivas Gorur-Shandilya at 7:32 , 10 December 2014. Contact me at http://srinivas.gs/contact/
# 
# This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Internationa# License. 
# To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.

brew update
brew upgrade


# update youtube-dl 
youtube-dl -U
