#!/bin/bash
# kill troublesome processes
# 
# this was originally written to run on a server running Mac OS X. the problem was that some threads
# (especially something called perl5.12, which is very strange)

# define core variables
cpu_thresh=75 # in percent. above this, we will try to kill processes
n_proc_to_kill=5 # we will kill these many processes

((n_proc_to_kill++))

# first check if the CPU is being used intensively 
total_cpu=$(ps aux | awk {'sum+=$3;print sum'} | tail -n 1)
total_cpu=$( printf "%.0f" $total_cpu ) # because bash is so stupid that -gt comparison only works for integers
if [ $total_cpu -gt $cpu_thresh ]
then
	for (( c=2; c<=$n_proc_to_kill; c++ ))
	do 
		kill_me=$(ps aux | awk {'sum=$2;print sum'} | head -n $c | tail -n 1)
		echo $kill_me
		kill -9 $kill_me
	done


fi


