#!/bin/bash
# secure-share
# compresses chosen folder, uploads to server, and returns a publicly sharable link together with a username and password for accessing said folder. authentication done using apache htaccess
# % 
# % created by Srinivas Gorur-Shandilya at 10:20 , 09 April 2014. Contact me at http://srinivas.gs/contact/
# % 
# % This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
# % To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.

# make a random string
index=0
str=""
for i in {a..z}; do arr[index]=$i; index=`expr ${index} + 1`; done
for i in {A..Z}; do arr[index]=$i; index=`expr ${index} + 1`; done
for i in {0..9}; do arr[index]=$i; index=`expr ${index} + 1`; done
for i in {1..6}; do str="$str${arr[$RANDOM%$index]}"; done

# compress chosen folder
folder_name=$1
zip_name=$str".zip"
echo "Compressing into" $zip_name
zip -r -X -q $zip_name $1 # -X flag removes junk that Mac OS X adds

# make a new folder
folder_name=$(echo $zip_name | cut -d '.' -f1)
mkdir $folder_name
cp $zip_name $folder_name/

# make a password
str=""
for i in {a..z}; do arr[index]=$i; index=`expr ${index} + 1`; done
for i in {A..Z}; do arr[index]=$i; index=`expr ${index} + 1`; done
for i in {0..9}; do arr[index]=$i; index=`expr ${index} + 1`; done
for i in {1..6}; do str="$str${arr[$RANDOM%$index]}"; done

# secure the folder -- make the htpasswd file
htpasswd -bc $folder_name/.htpasswd user $str

# make the htaccess file
source=$(echo "AuthUserFile /Library/WebServer/Documents/"$folder_name"/.htpasswd")
echo $source >> $folder_name/.htaccess
echo "AuthType Basic" >> $folder_name/.htaccess
echo "AuthName "user"" >> $folder_name/.htaccess
echo "Require valid-user" >> $folder_name/.htaccess


# get the login name from some file (assumes you have public-key SSH set up)
login_id=$(<~/.server_id)

# copy to server
scp -r $folder_name $login_id:/Library/WebServer/Documents/

# copy public link, user name and password to clipboard 
echo -e $login_id/$folder_name "\nUser name: user\nPassword:" $str | pbcopy

# delete the .zip file we made
rm $zip_name

