#!/bin/bash
# this is meant to be called by upload-notifier
# 
# created by Srinivas Gorur-Shandilya at 9:59 , 09 December 2014. Contact me at http://srinivas.gs/contact/
# 
# This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International#License. 
# To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.

open ~/sync/uploads/
/code/auto-bots/tagfile.py jOqHdUxy8O ~/sync/uploads/$1